approvedGitRepositories:
  - "**"

defaultSemverRangePrefix: ^

enableGlobalCache: true

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 4320

npmPreapprovedPackages:
  - "@pob/*"
  - pob-dependencies
  - check-package-dependencies
  - alouette
  - alouette-icons
  - nightingale
  - nightingale-logger
